name: CI/CD Pipeline

on:
  workflow_dispatch:
    
  push:
    branches:
      - main
      # - 11-create-github-actions-workflow
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name myapp_container myapp:latest

    - name: Test with curl
      run: |
        sleep 10 # wait for the container to be fully up
        curl -f http://localhost:5000 | grep "hello"

    - name: Push Docker image to Docker Hub
      run: |
        docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/webserver-python:${{github.sha}}
        docker push ${{ secrets.DOCKER_USERNAME }}/webserver-python:${{github.sha}}